# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
      npm install snyk
      snyk auth $(SNYK_TOKEN)
    displayName: 'snyk install & auth'


- script: snyk test --unmanaged --print-dep-paths
    continueOnError: true
    displayName: 'Snyk Unmanaged Scan'

- script: snyk code test
    continueOnError: true
    displayName: 'Snyk Code Scan'

- script: snyk test --all-projects
    continueOnError: true
    displayName: 'Snyk NPM OSS Scan'